Repository dlang-community/D-Scanner, pull requests merged in 2018-11, with the labels that each got.

#712 Prevent running CI twice when PRs are originated from the origin
  .travis.yml
Labels: auto-merge-squash

#714 Prevent dub from blindly rebuilding every time
  dub.json
  dubhash.d
Labels: auto-merge

#724 fix #723 - segfault when running D-Scanner master against dparse repo with -S
  src/dscanner/analysis/unused.d
Labels: auto-merge, bug Fix

#726 fix #721 - prevent crash caused by DMD inliner
  makefile
Labels: auto-merge-squash

#725 fix #721 - disable GC while scanning to prevent GC to dispose some AST members
  .travis.sh
  src/dscanner/analysis/run.d
Labels: auto-merge-squash, bug Fix

#728 fix - adaptation to correct DIP 1009 impl. was incomplete
  .travis.sh
  src/dscanner/analysis/properly_documented_public_functions.d
  src/dscanner/analysis/unused.d
Labels: auto-merge-squash

#730 specify how -S works with folders and cwd
  README.md
Labels: auto-merge-squash
