Repository dlang-community/D-Scanner, pull requests merged in 2018-04, with the labels that each got.

#581 Adds a check for too much trusted scope, close #545
  README.md
  src/dscanner/analysis/config.d
  src/dscanner/analysis/run.d
  src/dscanner/analysis/trust_too_much.d
Labels: auto-merge-squash

#577 add IZ safeAccess util and refactor several && chains with it
  src/dscanner/analysis/assert_without_msg.d
  src/dscanner/analysis/mismatched_args.d
  src/dscanner/analysis/run.d
  src/dscanner/analysis/static_if_else.d
  src/dscanner/analysis/unmodified.d
  src/dscanner/analysis/useless_initializer.d
  src/dscanner/analysis/vcall_in_ctor.d
  src/dscanner/imports.d
  src/dscanner/main.d
  src/dscanner/readers.d
  src/dscanner/utils.d
Labels: auto-merge-squash

#589 fix #588 - trust_too_much false positive with alias decl
  src/dscanner/analysis/trust_too_much.d
Labels: auto-merge, trivial

#587 Don't use the dscanner prefix for the ModuleFilter in the config INI
  src/dscanner/analysis/config.d
Labels: trivial

#586 Fix #583 - False negative for missing parameter in Params
  src/dscanner/analysis/properly_documented_public_functions.d
Labels: Bug Fix, auto-merge, static analysis

#582 Fix #268 - Use the User's profile directory under Windows
  src/dscanner/main.d
Labels: auto-merge, windows

#590 Use -flto=full for the LDC release build
  makefile
Labels: auto-merge

#595 fix spaces indentation
  src/dscanner/main.d
Labels: auto-merge, trivial

#596 fix #195 - Unrecognized CLI options gives huge stacktrace
  src/dscanner/main.d
Labels: Bug Fix, auto-merge

#594 fix #278 - Weird: UTF-16LE encoding is unsupported
  src/dscanner/utils.d
Labels: Bug Fix, auto-merge

#600 Don't run the whole testsuite on special tag builds
  .travis.yml
Labels: auto-merge

#584 Fix #438 - check for __gshared and immutable redundancies
  README.md
  src/dscanner/analysis/config.d
  src/dscanner/analysis/redundant_storage_class.d
  src/dscanner/analysis/run.d
Labels: auto-merge

#606 Fix #601 - dscanner should not complain about Params section when there's no ddoc
  src/dscanner/analysis/properly_documented_public_functions.d
Labels: auto-merge

#605 Generate a valid version for the DUB build
  dub.json
  src/dscanner/dscanner_version.d
Labels: auto-merge

#608 fix all cases of mixed tabs and spaces
  src/dscanner/analysis/allman.d
  src/dscanner/analysis/auto_function.d
  src/dscanner/analysis/base.d
  src/dscanner/analysis/final_attribute.d
  src/dscanner/analysis/if_constraints_indent.d
  src/dscanner/analysis/imports_sortedness.d
  src/dscanner/analysis/label_var_same_name_check.d
  src/dscanner/analysis/lambda_return_check.d
  src/dscanner/analysis/objectconst.d
  src/dscanner/analysis/properly_documented_public_functions.d
  src/dscanner/analysis/unmodified.d
  src/dscanner/utils.d
Labels: auto-merge

#609 fix #607 - Dscanner should warn about missing throws section in ddoc
  src/dscanner/analysis/properly_documented_public_functions.d
Labels: auto-merge-squash, enhancement

#611 Change trust_too_much message which was slightly ambiguous
  src/dscanner/analysis/trust_too_much.d
Labels: auto-merge-squash

#603 Build binaries for Windows on Travis
  .travis.yml
  release-windows.sh
Labels: auto-merge

#604 Use git --describe tags as version string
  makefile
  src/dscanner/dscanner_version.d
  src/dscanner/main.d
Labels: auto-merge

#616 Set all checkers class "final"
  src/dscanner/analysis/alias_syntax_check.d
  src/dscanner/analysis/allman.d
  src/dscanner/analysis/asm_style.d
  src/dscanner/analysis/assert_without_msg.d
  src/dscanner/analysis/auto_ref_assignment.d
  src/dscanner/analysis/builtin_property_names.d
  src/dscanner/analysis/comma_expression.d
  src/dscanner/analysis/constructors.d
  src/dscanner/analysis/del.d
  src/dscanner/analysis/duplicate_attribute.d
  src/dscanner/analysis/enumarrayliteral.d
  src/dscanner/analysis/explicitly_annotated_unittests.d
  src/dscanner/analysis/fish.d
  src/dscanner/analysis/function_attributes.d
  src/dscanner/analysis/has_public_example.d
  src/dscanner/analysis/if_constraints_indent.d
  src/dscanner/analysis/if_statements.d
  src/dscanner/analysis/ifelsesame.d
  src/dscanner/analysis/imports_sortedness.d
  src/dscanner/analysis/incorrect_infinite_range.d
  src/dscanner/analysis/label_var_same_name_check.d
  src/dscanner/analysis/lambda_return_check.d
  src/dscanner/analysis/length_subtraction.d
  src/dscanner/analysis/line_length.d
  src/dscanner/analysis/local_imports.d
  src/dscanner/analysis/logic_precedence.d
  src/dscanner/analysis/numbers.d
  src/dscanner/analysis/objectconst.d
  src/dscanner/analysis/opequals_without_tohash.d
  src/dscanner/analysis/pokemon.d
  src/dscanner/analysis/properly_documented_public_functions.d
  src/dscanner/analysis/range.d
  src/dscanner/analysis/redundant_attributes.d
  src/dscanner/analysis/redundant_parens.d
  src/dscanner/analysis/redundant_storage_class.d
  src/dscanner/analysis/static_if_else.d
  src/dscanner/analysis/stats_collector.d
  src/dscanner/analysis/trust_too_much.d
  src/dscanner/analysis/undocumented.d
  src/dscanner/analysis/unmodified.d
  src/dscanner/analysis/unused.d
  src/dscanner/analysis/useless_assert.d
  src/dscanner/analysis/vcall_in_ctor.d
Labels: auto-merge, trivial

#615 fix #610 - False Negative For Missing Template Param In Ddoc
  src/dscanner/analysis/properly_documented_public_functions.d
Labels: auto-merge, bug Fix

#618 bump version number
  src/dscanner/dscanner_version.d
Labels: auto-merge, trivial

#619 Upload the Windows binary to the releases instead of the raw executable
  .travis.yml
Labels: auto-merge
