Repository dlang-community/D-Scanner, pull requests merged in 2018-06, with the labels that each got.

#646 fix #645 - False positive, Else branch identical to Then branch with incomplete IfStatement
  src/dscanner/analysis/ifelsesame.d
Labels: auto-merge, trivial

#657 fix #656 - Crash due to unsafe access in infinite range check
  src/dscanner/analysis/incorrect_infinite_range.d
Labels: auto-merge

#661 fix #658 - warning about non-const should not be emitted if the metho…
  src/dscanner/analysis/objectconst.d
Labels: auto-merge, bug Fix

#660 fix #659 - has opEquals but not toHash warning even if opEquals is di…
  src/dscanner/analysis/opequals_without_tohash.d
Labels: auto-merge, bug Fix

#662 Put the name of the variable which has a useless init between back ticks
  src/dscanner/analysis/useless_initializer.d
Labels: auto-merge, trivial

#667 fix #666 - False positive for "trust too much"
  src/dscanner/analysis/trust_too_much.d
Labels: bug Fix

#668 fix #665 - The check for auto function without return doesn't handle "implicit auto functions"
  src/dscanner/analysis/auto_function.d
Labels: enhancement

#670 Improve auto-versioning
  .gitignore
  build.bat
  release-windows.sh
  src/dscanner/dscanner_version.d
Labels: auto-merge

#592 Auto-deploy to DockerHub
  .travis.yml
  Dockerfile
  README.md
Labels: auto-merge
